version: "3.8"
services:
  nginx:
    image: nginx:1.23.1
    ports:
      - target: 80
        published: 82
        protocol: tcp
    configs:
    - source: nginx_conf
      target: /etc/nginx/nginx.conf
    - source: default_nginx
      target: /etc/nginx/conf.d/default.conf
    volumes:
      - type: volume
        source: files
        target: /var/www/html
    networks:
      - traefik-public
      - internal
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == worker]
      restart_policy: 
        condition: on-failure
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.sirias.rule=Host(`sirias.nhrs.ru`)"
        - "traefik.http.routers.sirias.service=sirias"
        - "traefik.http.services.sirias.loadbalancer.server.port=80" 
        - "traefik.http.services.sirias.loadbalancer.sticky=true"
        - "traefik.http.routers.sirias.entrypoints=web"
        - "traefik.docker.network=traefik-public"

  php-fpm:
    image: ilfatgub/php-fpm:7.2
    environment:
      TZ: "Asia/Yekaterinburg"
      SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      SQL_IP: ${SQL_IP}
      cookieValidationKey: ${cookieValidationKey_sirias}
    configs:
      - source: php_ini
        target: /usr/local/etc/php/conf.d/custom.ini
    networks:
      - internal
    volumes:
      - type: volume
        source: files
        target: /var/www/html
    deploy:
      mode: replicated
      replicas: 2
      placement:
        constraints: [node.role == worker]
      restart_policy: 
        condition: on-failure
configs:
  default_nginx:
    external: true
  nginx_conf:
    external: true
  php_ini:
    external: true

volumes:
  files:
    driver_opts:
      type: nfs
      o: addr=172.17.82.26,rw,nolock
      device: ":/var/www/html/sirias.nhrs.ru"

networks:
  traefik-public:
    external: true
  internal:
    driver: overlay