version: "3.8"
services:
  nginx:
    image: nginx:1.23.1
    ports:
      - target: 80
        published: 82
        protocol: tcp
    configs:
    - source: nginx_conf
      target: /etc/nginx/nginx.conf
    - source: default_nginx
      target: /etc/nginx/conf.d/default.conf
    volumes:
      - type: volume
        source: sirias_public
        target: /var/www/html/public
      - type: volume
        source: sirias_logs
        target: /var/log/nginx
    depends_on:
      -  php-fpm
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == worker]
      restart_policy: 
        condition: on-failure

  php-fpm:
    image: ilfatgub/php-fpm:7.2_v1
    environment:
      TZ: "Asia/Yekaterinburg"
      SQL_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD}
      SQL_IP: ${SQL_IP}
      cookieValidationKey: ${cookieValidationKey_sirias}
    configs:
      - source: php_ini
        target: /usr/local/etc/php/conf.d/custom.ini
    volumes:
      - type: volume
        source: sirias_public
        target: /var/www/html/public
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == worker]
      restart_policy: 
        condition: on-failure
configs:
  default_nginx:
    external: true
  nginx_conf:
    external: true
  php_ini:
    external: true

volumes:
  sirias_public:
    driver_opts:
      type: nfs
      o: addr=172.17.82.26,rw,nolock
      device: ":/var/www/html/sirias.nhrs.ru/public"
  sirias_logs:
    driver_opts:
      type: nfs
      o: addr=172.17.82.26,rw,nolock
      device: ":/var/www/html/sirias.nhrs.ru/logs/nginx"